language: python
python:
  - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.6"
  # - "nightly" # currently points to 3.7-dev

install:
  - python setup.py install
  - pip install httmock
  - pip install tox

script: py.test ./tests
